### ISSUE TITLE
Feature Request: Budget Balance

### ISSUE THREAD

**Issue by Ionshard** [jlvcm/ha-actualbudget#18]
In actualpy v0.8.0 the possibility of getting the [current balance of a budget](https://github.com/bvanelli/actualpy/commit/4921908968400d61f8e5af0c87ae03263825d99d) was added. 

It would be nice if this information was also included into Home Assistant. In fact, this data is actually the entire reason I was looking to add the Actual HA Integration. I want to add a gauge panel to the dashboard in my living room that shows how much money is left in the "Take Out" budget so my partner and I can tell at a glance whether we can just be lazy and order take out or if we have to actually cook something 🤣

Since HA supports Pydantic v2 now and there is no longer a custom `actualpy` fork in play it should be easy to upgrade the `actualpy` requirement to get access to this functionality. I am will to complete this work myself if that would be desired.

However, I am creating this issue to discuss the method to implement this.

Currently this integration creates a "Budget Sensor" with the budget amount as the state and all other information as extra attributes. It would be trivial to add the `balance` as one of these extra attributes.

However, as I have stated I actually care more about the current balance than I do about the amount. Having the `balance` as an attribute would make it more annoying to deal with. For example it would make it very difficult to add that as a card to the dashboard.

So instead would it make more sense to add a new sensor for this information and refactor the integration to provide multiple sensors for each budget? If so, this also ties into issue #17 since the IDs for the current sensors do not include the sensor type.

Let me know which direction would be preferential to pursue?

**Comment by jlvcm** [comment]
i'm ok with this change we just need to keep an eye on the amount of queries, but i didn't had time to check on performance yet,

my focus now that we are using the original actualpy version is to publish this into hacs so we can control version a bit better with tags, until then, i'm ok with breaking old configurations and big refactors, i just want to avoid leaving it in a totally broken state

**Comment by Fywqdk** [comment]
Would it make sense to have the balance/remaining budget (that's really also what I primarily want for an easy glance at our budget both for me and my wife) as the primary target when fetching the budget? Then the set budget amount (which is probably changed less often) could be fetched less often or even with a callable service so it could be tied to a button in HA? I am thinking it would require little if I have changed the budget in Actual to press a button in HA to update those values, whereas the current balance could change several times a day (or several times per minute while updating transactions).

I am still trying to wrap my head around the code but I will be happy to test things until I can start contributing in a meaningful way.

**Comment by Ionshard** [comment]
> Would it make sense to have the balance/remaining budget (that's really also what I primarily want for an easy glance at our budget both for me and my wife) as the primary target when fetching the budget? Then the set budget amount (which is probably changed less often) could be fetched less often or even with a callable service so it could be tied to a button in HA? I am thinking it would require little if I have changed the budget in Actual to press a button in HA to update those values, whereas the current balance could change several times a day (or several times per minute while updating transactions).

The problem is that the remaining balance in a budget isn't a stored value somewhere that can just be retrieved. Its actually a derived value via doing the math: `budget amount for month - SUM(transactions for month)` ... so the current amount and the balance are closely related. So it would be impossible to update one and not the other because only the amount exists 😄 

In `actualpy` v7 they introduced the ability to get the budget's balance but that's just a utility function that does the above math for you. So ultimately if we want the budget balance in HA we have to fetch the budget amount, so it'd make sense to just pull both when running the scheduled update.

The problem I am describing in my OP is that Home Assistant only allows 1 value to be the state of a sensor, e.g. a switch is `on/off` or a temperature is just `21`. If you have a fancy thermostat that reads both temperature and humidity then it will actually create 2 separate sensors, one for temperature and another for humidity. I think this is what makes the most sense here too and that is what I am proposing. The Actual integration would create 2 sensors per budget, one for total amount and another for balance.

**Comment by Fywqdk** [comment]
Yeah I decided to play around with this a bit more and I think I have a much better understanding of it now. I also think I have a solution though, currently running last tests on my own setup before updating my fork.

**Comment by jlvcm** [comment]
hey @Fywqdk thanks for all your work 🙏 

i've merged it and released a pre release version and can be used now by selecting the version

<img width="696" alt="Image" src="https://github.com/user-attachments/assets/b00eb7d3-e3cc-45a6-b222-07b318f35fee" />

@Ionshard , let me know what do you think, if this works for you or if another idea/improvement i can improve on.


thanks everyone!

**Comment by antonvanderwel** [comment]
Am I allowed to ask the silly amateur question?
I can code, but I am also very new to homeassistant. I install the above beta and I currently see only the on and offbudget account as sensors. I am not able to see any other (budget) sensor. I also did not discovery any attributes linked to the account sensors.

How do I access the aforementioned budgets?

**Comment by Fywqdk** [comment]
Sorry for missing this. I would say it should show up eventually but it takes quite a while to load and update all the budget data, so it can take some time. Also I have been having quite a few problems with my connection being dropped which then crashes the integration until HA is reloaded, but I suspect that has more to do with my Actual Budget container running on my Synology NAS.

**Comment by rob-nichols** [comment]
Was this rolled into production? I'm running v2.01 and it still isn't showing up.
